### ISSUE TITLE
HSTS: Do not set includeSubDomains by default

### ISSUE THREAD

**Issue by DanielRuf** [kielcoding/KielCodingSecurityHeaders#3]
Setting `includeSubDomains` affects all subdomains and can have a negative impact when subdomains do not have a (valid) TLS cert. Because disabling / resetting this can often just done by setting the `max-age` to `0`.

As there are sometimes subdomains on the same host used by the hoster with selfsigned certs or internal subdomains it may break these. Also it is harder to debug where the HSTS is forced.

What do you think?

https://github.com/kielcoding/KielCodingSecurityHeaders/blob/93eb08ad84c9e8d8a3170d2a42aeba5debbaef3a/Resources/config.xml#L52

**Comment by DanielRuf** [comment]
Similar thing with the Referrer-Policy setting `no-referrer`. The default is `no-referrer-when-downgrade` and probably recommended.

**Comment by kielcoding** [comment]
Sounds like a good idea to change the default values.
